networks:
  switchnet:

services:
  dataplane:
    build:
      context: ./dataplane-rs
    container_name: dataplane
    networks:
      - switchnet
    # The Dockerfile for dataplane should define CMD ["dataplane_rs"]
    # If not, you can uncomment the next line:
    # command: ["dataplane_rs"]

  controlplane:
    build:
      context: ./control-plane-go
    container_name: controlplane
    ports:
      - "8080:8080"
    networks:
      - switchnet
    depends_on:
      - dataplane
    # The Dockerfile should define CMD ["switchapi"]
    # If not, uncomment:
    # command: ["switchapi"]

  tests:
    build:
      context: ./tests/integration
    container_name: integration-tests
    depends_on:
      - dataplane
      - controlplane
    networks:
      - switchnet
    # Command comes from tests/integration/Dockerfile (CMD ["./test.sh"])
