networks:
  switchnet:
    driver: bridge

services:
  dataplane:
    build:
      context: ./dataplane-rs
      dockerfile: Dockerfile
    container_name: dataplane
    networks:
      - switchnet
    ports:
      - "8081:8080" # External 8081 -> internal 8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 2s

  controlplane:
    build:
      context: ./control-plane-go
      dockerfile: Dockerfile
    container_name: controlplane
    networks:
      - switchnet
    ports:
      - "8080:8080" # REST API port
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 2s
      retries: 10
      start_period: 5s
      timeout: 2s

  integration-tests:
    build:
      context: ./integration-tests
      dockerfile: Dockerfile
    container_name: integration-tests
    networks:
      - switchnet
    depends_on:
      dataplane:
        condition: service_healthy
      controlplane:
        condition: service_healthy
    environment:
      DATAPLANE_HOST: dataplane
      DATAPLANE_PORT: 8080
      CONTROLPLANE_HOST: controlplane
      CONTROLPLANE_PORT: 8080
    command: ["./run_tests.sh"]