networks:
  switchnet:

services:
  dataplane:
    build:
      context: ./dataplane-rs
    container_name: dataplane
    networks:
      - switchnet
    # Keep container alive until real dataplane code is implemented
    command: ["sh", "-c", "echo dataplane stub container running && tail -f /dev/null"]  
      
  controlplane:
    build:
      context: ./control-plane-go
    container_name: controlplane
    ports:
      - "8080:8080"
    networks:
      - switchnet
    depends_on:
      - dataplane
    # The Dockerfile should define CMD ["switchapi"]
    # If not, uncomment:
    # command: ["switchapi"]

  tests:
    build:
      context: ./tests/integration
    container_name: integration-tests
    depends_on:
      - dataplane
      - controlplane
    networks:
      - switchnet
    # Command comes from tests/integration/Dockerfile (CMD ["./test.sh"])
