services:
  dataplane:
    build:
      context: ./dataplane-rs
    container_name: dataplane
    # use the CMD from Dockerfile (do not override)
    networks:
      - switchnet

  controlplane:
    build:
      context: ./control-plane-go
    container_name: controlplane
    ports:
      - "8080:8080"
    networks:
      - switchnet
    depends_on:
      - dataplane

  tests:
    build:
      context: ./tests/integration
    container_name: integration-tests
    depends_on:
      - dataplane
      - controlplane
    networks:
      - switchnet
    command: ["./test.sh"]

networks:
  switchnet:
    driver: bridge
