name: CI

on:
  push:
  pull_request:

jobs:
  rust-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy

      - name: Format check (Rust)
        run: cd dataplane-rs && cargo fmt --all -- --check

      - name: Lint (Rust)
        run: cd dataplane-rs && cargo clippy --all-targets -- -D warnings

      - name: Build & Test Rust dataplane
        run: |
          cd dataplane-rs
          cargo build --release
          cargo test --verbose

  go-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Format check (Go)
        run: cd control-plane-go && gofmt -s -l . && test -z "$(gofmt -s -l .)"

      - name: Lint (Go)
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0
          working-directory: control-plane-go

      - name: Build & Test Go control plane
        run: |
          cd control-plane-go
          go build ./...
          go test -race ./...

  integration-tests:
    runs-on: ubuntu-latest
    needs: [rust-checks, go-checks]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Install Docker Compose v2 (CLI plugin)
      - name: Install Docker Compose
        run: |
          mkdir -p ~/.docker/cli-plugins/
          curl -SL https://github.com/docker/compose/releases/download/v2.29.1/docker-compose-linux-x86_64 \
            -o ~/.docker/cli-plugins/docker-compose
          chmod +x ~/.docker/cli-plugins/docker-compose
          docker compose version

      - name: Build test harness
        run: docker compose -f docker-compose.test.yml build

      - name: Run integration tests
        run: docker compose -f docker-compose.test.yml up --exit-code-from tests

